from fastapi import APIRouter
from ..db.supabase_client import supabase_request
from ..ai.model import answer_query

router = APIRouter(prefix='/faq', tags=['faq'])


@router.get('/')
async def get_faqs():
    """Retrieves all Frequently Asked Questions (FAQs) from the database.

    Returns:
        A list of FAQ objects, each typically containing a question and an answer.
    """
    r = await supabase_request('GET', 'faq')
    return r.get('data')


@router.post('/ask')
async def ask_question(payload: dict):
    """Answers a user's question using a pre-trained AI model.

    Args:
        payload: A dictionary containing the user's question under the key 'question'.

    Returns:
        The answer generated by the AI model.
    """
    q = payload.get('question')
    return await answer_query(q)

